# Build
dest: _gh_pages


# Site metadata
title: Blog
lead: false
description: >
  "Blog theme, for Assemble."

# License info
license:
  type: MIT License
  url: ./license/index.html


# URLs
blog: http://assemble.io/blog
repo: https://github.com/assemble/assemble
download:
  source: <%= site.repo %>/archive/master.zip
  source: <%= site.repo %>/archive/master.zip


# SEO/SEM
google_analytics: false
google_site_id: false


# Comments
disqus:
  shortname: assemble


# Social
social:
  twitter:
    via: jonschlinkert
    username: assemble
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
social:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false


